import TextSlider from "@/components/TextSlider";
import ImageSlider from "@/components/ImageSlider";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AI Marketing Elements</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <h1 className="text-4xl font-bold mt-10 bg-black text-white rounded-full px-20 py-10">
          AI Marketing Elements
        </h1>
        <TextSlider />
        <ImageSlider />
      </main>
    </>
  );
}
